# Generated by Django 4.0.4 on 2022-06-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_of_purchase',
            field=models.DateField(auto_now_add=True),
        ),
    ]
